const SALE_ACTION_TYPES = {
  INITIAL_SALES_FETCH_START: "INITIAL_SALES_FETCH_START",
  INITIAL_SALES_FETCH_FAIL: "INITIAL_SALES_FETCH_FAIL",
  INITIAL_SALES_FETCH_SUCCESS: "INITIAL_SALES_FETCH_SUCCESS",
  LOAD_MORE_SALES_START: "LOAD_MORE_SALES_START",
  LOAD_MORE_SALES_FAIL: "LOAD_MORE_SALES_FAIL",
  LOAD_MORE_SALES_SUCCESS: "LOAD_MORE_SALES_SUCCESS",
  NO_MORE_TO_LOAD: "NO_MORE_TO_LOAD"
};

export default SALE_ACTION_TYPES;
