const SALE_ACTION_TYPES = {
  START_INITIAL_SALES_FETCH: "START_INITIAL_SALES_FETCH",
  INITIAL_SALES_FETCH_FAIL: "INITIAL_SALES_FETCH_FAIL",
  INITIAL_SALES_FETCH_SUCCESS: "INITIAL_SALES_FETCH_SUCCESS",
  START_LOADING_MORE_SALES: "START_LOADING_MORE_SALES",
  LOADING_MORE_SALES_FAIL: "LOADING_MORE_SALES_FAIL",
  LOADING_MORE_SALES_SUCCESS: "LOADING_MORE_SALES_SUCCESS",
  NO_MORE_SALES_TO_LOAD: "NO_MORE_SALES_TO_LOAD",
  START_SALES_SUMMARY_FETCH: "START_SALES_SUMMARY_FETCH",
  SALES_SUMMARY_FETCH_FAIL: "SALES_SUMMARY_FETCH_FAIL",
  SALES_SUMMARY_FETCH_SUCCESS: "SALES_SUMMARY_FETCH_SUCCESS"
};

export default SALE_ACTION_TYPES;
