const PRODUCT_CATEGORY_ACTION_TYPES = {
  INITIAL_PRODUCT_CATEGORIES_FETCH_START:
    "INITIAL_PRODUCT_CATEGORIES_FETCH_START",
  INITIAL_PRODUCT_CATEGORIES_FETCH_FAIL:
    "INITIAL_PRODUCT_CATEGORIES_FETCH_FAIL",
  INITIAL_PRODUCT_CATEGORIES_FETCH_SUCCESS:
    "INITIAL_PRODUCT_CATEGORIES_FETCH_SUCCESS",
  LOAD_MORE_PRODUCT_CATEGORIES_START: "LOAD_MORE_PRODUCT_CATEGORIES_START",
  LOAD_MORE_PRODUCT_CATEGORIES_FAIL: "LOAD_MORE_PRODUCT_CATEGORIES_FAIL",
  LOAD_MORE_PRODUCT_CATEGORIES_SUCCESS: "LOAD_MORE_PRODUCT_CATEGORIES_SUCCESS",
  NO_MORE_TO_LOAD: "NO_MORE_TO_LOAD",
  START_CATEGORY_DELETE_BY_ID: "START_CATEGORY_DELETE_BY_ID",
  CATEGORY_DELETE_BY_ID_FAIL: "CATEGORY_DELETE_BY_ID_FAIL",
  CATEGORY_DELETE_BY_ID_SUCCESS: "CATEGORY_DELETE_BY_ID_SUCCESS",
  CREATE_NEW_CATEGORY: "CREATE_NEW_CATEGORY",
  CREATE_NEW_CATEGORY_FAIL: "CREATE_NEW_CATEGORY_FAIL",
  CREATE_NEW_CATEGORY_SUCCESS: "CREATE_NEW_CATEGORY_SUCCESS"
};

export default PRODUCT_CATEGORY_ACTION_TYPES;
