const PRODUCT_CATEGORY_ACTION_TYPES = {
  INITIAL_PRODUCT_CATEGORIES_FETCH_START:
    "INITIAL_PRODUCT_CATEGORIES_FETCH_START",
  INITIAL_PRODUCT_CATEGORIES_FETCH_FAIL:
    "INITIAL_PRODUCT_CATEGORIES_FETCH_FAIL",
  INITIAL_PRODUCT_CATEGORIES_FETCH_SUCCESS:
    "INITIAL_PRODUCT_CATEGORIES_FETCH_SUCCESS",
  LOAD_MORE_PRODUCT_CATEGORIES_START: "LOAD_MORE_PRODUCT_CATEGORIES_START",
  LOAD_MORE_PRODUCT_CATEGORIES_FAIL: "LOAD_MORE_PRODUCT_CATEGORIES_FAIL",
  LOAD_MORE_PRODUCT_CATEGORIES_SUCCESS: "LOAD_MORE_PRODUCT_CATEGORIES_SUCCESS",
  NO_MORE_TO_LOAD: "NO_MORE_TO_LOAD"
};

export default PRODUCT_CATEGORY_ACTION_TYPES;
