const PRODUCT_CATEGORY_ACTION_TYPES = {
  START_INITIAL_PRODUCT_CATEGORIES_FETCH:
    "START_INITIAL_PRODUCT_CATEGORIES_FETCH",
  INITIAL_PRODUCT_CATEGORIES_FETCH_FAIL:
    "INITIAL_PRODUCT_CATEGORIES_FETCH_FAIL",
  INITIAL_PRODUCT_CATEGORIES_FETCH_SUCCESS:
    "INITIAL_PRODUCT_CATEGORIES_FETCH_SUCCESS",
  START_LOADING_MORE_PRODUCT_CATEGORIES:
    "START_LOADING_MORE_PRODUCT_CATEGORIES",
  LOADING_MORE_PRODUCT_CATEGORIES_FAIL: "LOADING_MORE_PRODUCT_CATEGORIES_FAIL",
  LOADING_MORE_PRODUCT_CATEGORIES_SUCCESS:
    "LOADING_MORE_PRODUCT_CATEGORIES_SUCCESS",
  NO_MORE_PRODUCT_CATEGORIES_TO_LOAD: "NO_MORE_PRODUCT_CATEGORIES_TO_LOAD",
  START_CATEGORY_DELETE_BY_ID: "START_CATEGORY_DELETE_BY_ID",
  CATEGORY_DELETE_BY_ID_FAIL: "CATEGORY_DELETE_BY_ID_FAIL",
  CATEGORY_DELETE_BY_ID_SUCCESS: "CATEGORY_DELETE_BY_ID_SUCCESS",
  CREATE_NEW_CATEGORY: "CREATE_NEW_CATEGORY",
  CREATE_NEW_CATEGORY_FAIL: "CREATE_NEW_CATEGORY_FAIL",
  CREATE_NEW_CATEGORY_SUCCESS: "CREATE_NEW_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_BY_ID: "UPDATE_CATEGORY_BY_ID",
  UPDATE_CATEGORY_BY_ID_FAIL: "UPDATE_CATEGORY_BY_ID_FAIL",
  UPDATE_CATEGORY_BY_ID_SUCCESS: "UPDATE_CATEGORY_BY_ID_SUCCESS"
};

export default PRODUCT_CATEGORY_ACTION_TYPES;
