export const DARK_THEME = {
  backgroundColor: "#1a1a1a",
  backgroundColorLight: "#2b2b2b",
  backgroundColorLighter: "#4f4f4f",
  textColor: "#eee",
  primary: "#E8E8E8",
  primaryLight: "#eee",
  secondary: "#3498db",
  secondaryLight: "aliceblue",
  secondaryDarkColor: "#1a1a1a",
  primaryBorderColor: "white",
  primarySkeletonPulseColor: "#2b2b2b",
  secondarySkeletonPulseColor: "#4a4949",
  primaryFormColor: "white",
  boxShadow: "none",
  modalBackgroundColor: "#2b2b2b",
  overlayBackgroundColor: "rgba(71, 71, 71, 0.9)",
  readOnlyBackgroundColor: "#5c5c5c",
  dashboardBackgroundColor: "black",
  dashboardTextColor: "white"
};

export const LIGHT_THEME = {
  backgroundColor: "white",
  backgroundColorLight: "#e6f1f2",
  backgroundColorLighter: "#ccc",
  textColor: "black",
  primary: "#4a4a4a",
  primaryLight: "#4a4a4a",
  secondary: "#3498db",
  secondaryLight: "aliceblue",
  secondaryDarkColor: "#060b26",
  primaryBorderColor: "rgba(226, 232, 240, 1)",
  primarySkeletonPulseColor: "gainsboro",
  secondarySkeletonPulseColor: "#f8f8f8",
  primaryFormColor: "black",
  boxShadow: "0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22)",
  modalBackgroundColor: "white",
  overlayBackgroundColor: "rgba(255, 255, 255, 0.9)",
  readOnlyBackgroundColor: "#dddddd",
  dashboardBackgroundColor: "#060b26",
  dashboardTextColor: "#3498db"
};
