const CART_ACTION_TYPES = {
  TOGGLE_CART_VISIBILITY: "TOGGLE_CART_VISIBILITY",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CHANGE_QUANTITY: "CHANGE_QUANTITY",
  CLEAR_CART: "CLEAR_CART"
};

export default CART_ACTION_TYPES;
