const CART_ACTION_TYPES = {
  TOGGLE_CART_VISIBILITY: "TOGGLE_CART_VISIBILITY",
  // ADD_TO_CART: "ADD_TO_CART",
  // REMOVE_FROM_CART: "REMOVE_FROM_CART",
  // CHANGE_QUANTITY: "CHANGE_QUANTITY",
  START_ADD_TO_CART: "START_ADD_TO_CART",
  START_REMOVE_FROM_CART: "START_REMOVE_FROM_CART",
  START_CHANGE_QUANTITY: "START_CHANGE_QUANTITY",
  UPDATE_CART: "UPDATE_CART",
  CLEAR_CART: "CLEAR_CART",
  RESTORE_CART: "RESTORE_CART"
};

export default CART_ACTION_TYPES;
