const CART_ACTION_TYPES = {
  TOGGLE_CART_VISIBILITY: "TOGGLE_CART_VISIBILITY",
  START_ADD_TO_CART: "START_ADD_TO_CART",
  START_REMOVE_FROM_CART: "START_REMOVE_FROM_CART",
  START_CHANGE_QUANTITY: "START_CHANGE_QUANTITY",
  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_FAIL: "UPDATE_CART_FAIL",
  CLEAR_CART: "CLEAR_CART",
  RESTORE_CART: "RESTORE_CART"
};

export default CART_ACTION_TYPES;
