const WISHLIST_ACTION_TYPES = {
  START_WISHLISTS_FETCH: "START_WISHLISTS_FETCH",
  WISHLISTS_FETCH_FAIL: "WISHLISTS_FETCH_FAIL",
  WISHLISTS_FETCH_SUCCESS: "WISHLISTS_FETCH_SUCCESS",
  FETCH_WISHLIST_BY_ID_START: "FETCH_WISHLIST_BY_ID_START",
  FETCH_WISHLIST_BY_ID_FAIL: "FETCH_WISHLIST_BY_ID_FAIL",
  FETCH_WISHLIST_BY_ID_SUCCESS: "FETCH_WISHLIST_BY_ID_SUCCESS",
  START_WISHLIST_DELETE_BY_ID: "START_WISHLIST_DELETE_BY_ID",
  WISHLIST_DELETE_BY_ID_FAIL: "WISHLIST_DELETE_BY_ID_FAIL",
  WISHLIST_DELETE_BY_ID_SUCCESS: "WISHLIST_DELETE_BY_ID_SUCCESS",
  CREATE_NEW_WISHLIST: "CREATE_NEW_WISHLIST",
  CREATE_WISHLIST_FAIL: "CREATE_WISHLIST_FAIL",
  CREATE_WISHLIST_SUCCESS: "CREATE_WISHLIST_SUCCESS",
  START_ADD_TO_WISHLIST: "START_ADD_TO_WISHLIST",
  START_REMOVE_FROM_WISHLIST: "START_REMOVE_FROM_WISHLIST",
  UPDATE_WISHLIST_FAIL: "UPDATE_WISHLIST_FAIL",
  UPDATE_WISHLIST_SUCCESS: "UPDATE_WISHLIST_SUCCESS"
};

export default WISHLIST_ACTION_TYPES;
