const COLLECTION_ACTION_TYPES = {
  FETCHING_COLLECTION_FROM_DB: "FETCHING_COLLECTION_FROM_DB",
  FETCHING_COLLECTION_FAILED: "FETCHING_COLLECTION_FAILED",
  FETCHING_COLLECTION_SUCCESS: "FETCHING_COLLECTION_SUCCESS"
};

export default COLLECTION_ACTION_TYPES;
