const WISH_LIST_ACTION_TYPES = {
  START_WISH_LISTS_FETCH: "START_WISH_LISTS_FETCH",
  WISH_LISTS_FETCH_FAIL: "WISH_LISTS_FETCH_FAIL",
  WISH_LISTS_FETCH_SUCCESS: "WISH_LISTS_FETCH_SUCCESS",
  START_FETCH_WISH_LIST_BY_ID: "START_FETCH_WISH_LIST_BY_ID",
  FETCH_WISH_LIST_BY_ID_FAIL: "FETCH_WISH_LIST_BY_ID_FAIL",
  FETCH_WISH_LIST_BY_ID_SUCCESS: "FETCH_WISH_LIST_BY_ID_SUCCESS",
  START_WISH_LIST_DELETE_BY_ID: "START_WISH_LIST_DELETE_BY_ID",
  WISH_LIST_DELETE_BY_ID_FAIL: "WISH_LIST_DELETE_BY_ID_FAIL",
  WISH_LIST_DELETE_BY_ID_SUCCESS: "WISH_LIST_DELETE_BY_ID_SUCCESS",
  CREATE_NEW_WISH_LIST: "CREATE_NEW_WISH_LIST",
  CREATE_WISH_LIST_FAIL: "CREATE_WISH_LIST_FAIL",
  CREATE_WISH_LIST_SUCCESS: "CREATE_WISH_LIST_SUCCESS",
  START_ADD_TO_WISH_LIST: "START_ADD_TO_WISH_LIST",
  START_REMOVE_FROM_WISH_LIST: "START_REMOVE_FROM_WISH_LIST",
  START_WISH_LIST_UPDATE: "START_WISH_LIST_UPDATE",
  UPDATE_WISH_LIST_FAIL: "UPDATE_WISH_LIST_FAIL",
  UPDATE_WISH_LIST_SUCCESS: "UPDATE_WISH_LIST_SUCCESS"
};

export default WISH_LIST_ACTION_TYPES;
