const NOTIFICATION_ACTION_TYPES = {
  ADD_SUCCESS_NOTIFICATION: "ADD_SUCCESS_NOTIFICATION",
  ADD_ERROR_NOTIFICATION: "ADD_ERROR_NOTIFICATION",
  ADD_WARNING_NOTIFICATION: "ADD_WARNING_NOTIFICATION",
  ADD_INFO_NOTIFICATION: "ADD_INFO_NOTIFICATION",
  DELETE_NOTIFICATION: "DELETE_NOTIFICATION"
};

export default NOTIFICATION_ACTION_TYPES;
