const COLLECTION_ACTION_TYPES = {
  COLLECTION_FETCH_START: "COLLECTION_FETCH_START",
  COLLECTION_FETCH_FAIL: "COLLECTION_FETCH_FAIL",
  COLLECTION_FETCH_SUCCESS: "COLLECTION_FETCH_SUCCESS"
};

export default COLLECTION_ACTION_TYPES;
