const DIRECTORY_ACTION_TYPES = {
  CATEGORIES_FETCH_START: "CATEGORIES_FETCH_START",
  CATEGORIES_FETCH_SUCCESS: "CATEGORIES_FETCH_SUCCESS",
  CATEGORIES_FETCH_FAIL: "CATEGORIES_FETCH_FAIL"
};

export default DIRECTORY_ACTION_TYPES;
