const CHECKOUT_ACTION_TYPES = {
  START_CHECKOUT: "START_CHECKOUT",
  CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
  CHECKOUT_FAIL: "CHECKOUT_FAIL",
  START_RECORDING_SALE: "START_RECORDING_SALE",
  RECORDING_SALE_SUCCESS: "RECORDING_SALE_SUCCESS",
  RECORDING_SALE_FAIL: "RECORDING_SALE_FAIL"
};

export default CHECKOUT_ACTION_TYPES;
