const USER_ACTION_TYPES = {
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAIL: "SIGN_IN_FAIL",
  SIGN_IN_USER_FROM_SESSION: "SIGN_IN_USER_FROM_SESSION",
  LOG_OUT_START: "LOG_OUT_START",
  LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
  LOG_OUT_FAIL: "LOG_OUT_FAIL",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAIL: "SIGN_UP_FAIL",
  CLEAR_AUTH_ERRORS: "CLEAR_AUTH_ERRORS"
};

export default USER_ACTION_TYPES;
