const USER_ACTION_TYPES = {
  START_GOOGLE_SIGN_IN: "START_GOOGLE_SIGN_IN",
  START_EMAIL_SIGN_IN: "START_EMAIL_SIGN_IN",
  START_AUTO_SIGN_IN: "START_AUTO_SIGN_IN",
  SIGN_IN_FAIL: "SIGN_IN_FAIL",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  START_LOG_OUT: "START_LOG_OUT",
  LOG_OUT_FAIL: "LOG_OUT_FAIL",
  LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
  START_SIGN_UP: "START_SIGN_UP",
  SIGN_UP_FAIL: "SIGN_UP_FAIL"
};

export default USER_ACTION_TYPES;
