const PRODUCT_ACTION_TYPES = {
  INITIAL_PRODUCTS_FETCH_START: "INITIAL_PRODUCTS_FETCH_START",
  INITIAL_PRODUCTS_FETCH_FAIL: "INITIAL_PRODUCTS_FETCH_FAIL",
  INITIAL_PRODUCTS_FETCH_SUCCESS: "INITIAL_PRODUCTS_FETCH_SUCCESS",
  INITIAL_FETCH_PRODUCTS_BY_CATEGORY_START:
    "INITIAL_FETCH_PRODUCTS_BY_CATEGORY_START",
  LOAD_MORE_PRODUCTS_START: "LOAD_MORE_PRODUCTS_START",
  LOAD_MORE_PRODUCTS_BY_CATEGORY_START: "LOAD_MORE_PRODUCTS_BY_CATEGORY_START",
  LOAD_MORE_PRODUCTS_FAIL: "LOAD_MORE_PRODUCTS_FAIL",
  LOAD_MORE_PRODUCTS_SUCCESS: "LOAD_MORE_PRODUCTS_SUCCESS",
  NO_MORE_TO_LOAD: "NO_MORE_TO_LOAD"
};

export default PRODUCT_ACTION_TYPES;
