const PRODUCT_ACTION_TYPES = {
  PRODUCTS_FETCH_START: "PRODUCTS_FETCH_START",
  PRODUCTS_FETCH_FAIL: "PRODUCTS_FETCH_FAIL",
  PRODUCTS_FETCH_SUCCESS: "PRODUCTS_FETCH_SUCCESS",
  FETCH_PRODUCTS_BY_CATEGORY: "FETCH_PRODUCTS_BY_CATEGORY"
};

export default PRODUCT_ACTION_TYPES;
